source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
target "HLSleepClockApp" do
pod 'YYKit', '~> 1.0.9', :inhibit_warnings => true
pod 'SDWebImage', '~> 3.8.2', :inhibit_warnings => true
end

